<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UseCases\Comments\Commands\CreateCommand\**" />
    <Compile Remove="UseCases\Comments\Commands\DeleteCommand\**" />
    <EmbeddedResource Remove="UseCases\Comments\Commands\CreateCommand\**" />
    <EmbeddedResource Remove="UseCases\Comments\Commands\DeleteCommand\**" />
    <None Remove="UseCases\Comments\Commands\CreateCommand\**" />
    <None Remove="UseCases\Comments\Commands\DeleteCommand\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonalCollection.Domain\PersonalCollection.Domain.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <Folder Include="Commons\Mapping\" />
    <Folder Include="UseCases\Items\Commands\DeleteItem\" />
    <Folder Include="UseCases\Items\Commands\UpdateItem\" />
    <Folder Include="UseCases\Items\Queries\GetItems\" />
    <Folder Include="UseCases\Items\Queries\GetItem\" />
    <Folder Include="UseCases\Likes\Commands\CreateItem\" />
    <Folder Include="UseCases\Likes\Commands\DeleteItem\" />
    <Folder Include="UseCases\Likes\Commands\UpdateItem\" />
    <Folder Include="UseCases\Likes\Queries\GetItems\" />
    <Folder Include="UseCases\Likes\Queries\GetItem\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.6.0" />
    <PackageReference Include="MediatR" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="7.0.9" />
    <PackageReference Include="Serilog" Version="3.0.1" />
  </ItemGroup>

</Project>
